name: Test CLIENT

on:
  push:
    paths:
      - client/**
      - .github/workflows/test-front.yml

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install dependencies
        run: |
          cd client
          yarn install

      - name: Run tests
        run: |
          cd client
          yarn test
